Minor refactoring
vert-x3/vertx-sql-common pull request #63
Opened 2018-09-27 23:00 UTC by juanavelez

Some minor refactoring to remove duplicate code. Had to create static class HandlerUtil because complaints from codegen about static methods in interface.

Signed-off-by: Juan A. Velez <jvelez@chibchasoft.com>

2018-09-28 06:25 UTC, vietj commented on src/main/java/io/vertx/ext/sql/util/HandlerUtil.java
> +public final class HandlerUtil {
make the method package private

2018-09-28 06:25 UTC, vietj commented on src/main/java/io/vertx/ext/sql/util/HandlerUtil.java
> +  public static Handler<AsyncResult<ResultSet>> handleResultSetSingleRow(Handler<AsyncResult<@Nullable JsonArray>> handler) {
make the method package private

2018-09-28 06:25 UTC, vietj commented on src/main/java/io/vertx/ext/sql/util/HandlerUtil.java
> +  public static <T> Handler<AsyncResult<T>> closeAndHandleResult(SQLConnection conn, Handler<AsyncResult<T>> handler) {
make the method package private

2018-09-28 06:25 UTC, vietj requested changes
some changes required.

2018-10-09 01:37 UTC, juanavelez commented
@vietj I have made the requested changes. Please review. Thank you

2018-10-09 10:43 UTC, vietj approved these changes

2018-10-09 10:44 UTC, merged